# Generated by Django 5.1.7 on 2025-03-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_note_alter_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='note',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
